// Vendor category definitions
// priceId: set these in your Stripe dashboard, then add to Render env vars
export const VENDORS = [
  {
    id: 'electronics',
    name: 'Electronics Vendor',
    emoji: '📱',
    category: 'Electronics',
    tag: 'BEST DEAL',
    tagColor: 'from-purple-600 to-pink-500',
    desc: 'iPhones, Samsung, AirPods, headphones, smart watches, speakers & more. Direct supplier access.',
    items: ['iPhones from $10', 'Samsung Galaxy S24/S25', 'AirPods & headphones', 'Smart watches', 'JBL speakers', 'Dyson & accessories'],
    originalPrice: '$49.99',
    price: '$7.99',
    gradient: 'from-purple-900/40 via-purple-800/20 to-black',
    glowColor: 'rgba(147,51,234,0.4)',
    priceEnvKey: 'VITE_PRICE_ELECTRONICS',
  },
  {
    id: 'shoes',
    name: 'Shoes Vendor',
    emoji: '👟',
    category: 'Footwear',
    tag: 'POPULAR',
    tagColor: 'from-blue-600 to-purple-600',
    desc: 'Jordans, Nike, designer sneakers and more. Source heat at supplier prices.',
    items: ['Air Jordans', 'Nike Dunks', 'Designer sneakers', 'Yeezys', 'New Balance', 'Limited drops'],
    originalPrice: '$29.99',
    price: '$7.99',
    gradient: 'from-blue-900/30 via-purple-900/20 to-black',
    glowColor: 'rgba(59,130,246,0.3)',
    priceEnvKey: 'VITE_PRICE_SHOES',
  },
  {
    id: 'jewelry',
    name: 'Jewelry Vendor',
    emoji: '💎',
    category: 'Jewelry',
    tag: 'HIGH MARGIN',
    tagColor: 'from-yellow-500 to-orange-500',
    desc: 'Iced out chains, rings, bracelets, and pendants. High-margin products that flip fast.',
    items: ['Iced out chains', 'Diamond rings', 'Tennis bracelets', 'Pendants', 'Cuban links', 'Custom pieces'],
    originalPrice: '$29.99',
    price: '$7.99',
    gradient: 'from-yellow-900/20 via-purple-900/20 to-black',
    glowColor: 'rgba(234,179,8,0.2)',
    priceEnvKey: 'VITE_PRICE_JEWELRY',
  },
  {
    id: 'hoodies',
    name: 'Hoodie Vendor',
    emoji: '🧥',
    category: 'Streetwear',
    tag: 'TOP SELLER',
    tagColor: 'from-pink-600 to-purple-600',
    desc: 'Spider, Essential, designer hoodies at supplier cost. Best-selling resell category.',
    items: ['Spider hoodies', 'Essentials', 'Gallery Dept', 'Corteiz', 'Stussy', 'Designer brands'],
    originalPrice: '$19.99',
    price: '$7.99',
    gradient: 'from-pink-900/30 via-purple-900/20 to-black',
    glowColor: 'rgba(236,72,153,0.3)',
    priceEnvKey: 'VITE_PRICE_HOODIES',
  },
  {
    id: 'fragrance',
    name: 'Fragrance Vendor',
    emoji: '🌸',
    category: 'Fragrance',
    tag: 'FAST FLIP',
    tagColor: 'from-rose-500 to-pink-600',
    desc: 'Designer colognes and perfumes at unbeatable supplier prices. Easy sell every time.',
    items: ['Dior Sauvage', 'Creed Aventus', 'YSL Black Opium', 'Tom Ford', 'Chanel', 'Versace'],
    originalPrice: '$19.99',
    price: '$7.99',
    gradient: 'from-rose-900/20 via-purple-900/20 to-black',
    glowColor: 'rgba(244,63,94,0.2)',
    priceEnvKey: 'VITE_PRICE_FRAGRANCE',
  },
  {
    id: 'watches',
    name: 'Watches Vendor',
    emoji: '⌚',
    category: 'Watches',
    tag: 'NEW',
    tagColor: 'from-cyan-500 to-blue-600',
    desc: 'Smart watches, luxury timepieces, and designer watches at supplier pricing.',
    items: ['Smart watches', 'AP-style pieces', 'Richard Mille style', 'Rolex style', 'Casio G-Shock', 'Fossil'],
    originalPrice: '$19.99',
    price: '$7.99',
    gradient: 'from-cyan-900/20 via-purple-900/20 to-black',
    glowColor: 'rgba(6,182,212,0.2)',
    priceEnvKey: 'VITE_PRICE_WATCHES',
  },
  {
    id: 'clothing',
    name: 'Clothing Vendor',
    emoji: '👕',
    category: 'Clothing',
    tag: 'CONSISTENT',
    tagColor: 'from-green-500 to-teal-600',
    desc: 'T-shirts, joggers, tracksuits, and streetwear staples. Consistent sellers year-round.',
    items: ['Designer tees', 'Tracksuits', 'Joggers', 'Polo shirts', 'Cargo pants', 'Streetwear sets'],
    originalPrice: '$19.99',
    price: '$7.99',
    gradient: 'from-green-900/20 via-purple-900/20 to-black',
    glowColor: 'rgba(34,197,94,0.2)',
    priceEnvKey: 'VITE_PRICE_CLOTHING',
  },
  {
    id: 'bundle',
    name: 'All Access Bundle',
    emoji: '🔥',
    category: 'Bundle',
    tag: 'BEST VALUE',
    tagColor: 'from-purple-500 to-pink-500',
    desc: 'Every single vendor in one package. Electronics, shoes, jewelry, hoodies, fragrance, watches & clothing.',
    items: ['All 7 vendor categories', 'Electronics suppliers', 'Shoes & clothing', 'Jewelry & watches', 'Fragrance access', 'Lifetime updates'],
    originalPrice: '$55.93',
    price: '$24.99',
    gradient: 'from-purple-900/50 via-pink-900/20 to-black',
    glowColor: 'rgba(147,51,234,0.5)',
    priceEnvKey: 'VITE_PRICE_BUNDLE',
    featured: true,
  },
]

// Toast notification data — these cycle through to show social proof
export const TOAST_PRODUCTS = [
  'Electronics Vendor', 'Shoes Vendor', 'Jewelry Vendor', 'Hoodie Vendor',
  'Fragrance Vendor', 'Watches Vendor', 'All Access Bundle', 'Clothing Vendor',
  'Electronics Vendor', 'All Access Bundle',
]

export const TOAST_NAMES = [
  'Jordan M.', 'Tyler K.', 'Marcus J.', 'Kai B.', 'Jayden R.',
  'Alex T.', 'Ryan S.', 'Noah D.', 'Ethan W.', 'Liam F.',
  'Zoe C.', 'Maya L.', 'Andre P.', 'DeShawn H.', 'Chris V.',
]

// Ticker bar messages
export const TICKER_MESSAGES = [
  '🔥 Jordan just copped the Electronics Vendor — 2 mins ago',
  '💰 Marcus made $800 his first week with the Shoes Vendor',
  '📱 Tyler just got the All Access Bundle — 5 mins ago',
  '🧥 Kai is running up on Hoodie vendors right now',
  '💎 Jayden flipped his first jewelry order in 24hrs',
  '⌚ Ryan just purchased the Watches Vendor — just now',
  '🌸 Alex running Fragrance vendor — seeing crazy margins',
  '🔥 Noah copped the All Access Bundle — 1 min ago',
  '💰 Ethan made his money back in 3 days',
  '📦 Liam just got started with Electronics — 8 mins ago',
]
